## Visual test: displays triangulated grids generated by `makeGrid` on a Plane3 surface.
##
## The grid is computed from two closed 2D contours forming an outer boundary and a circular hole in the middle.

import std/[math]
import pkg/chroma
import rice
import sigeo/[core, curves2d, surfaces]
import ./drawutils

const
  outerRadius = 400
  holeRadius = 100
  resolution = 32

let gridW = (outerRadius * 2 + 2).float
let gridH = gridW
let margin = 30.0

let winW = int32(margin * 2 + gridW)
let winH = int32(margin * 2 + gridH)


let app = newVisualTest(
  title = "sigeo v_grids - grid bounded by 2d curves on 3d surface",
  size = ivec2(winW, winH),
  contentCenter = vec2(0, 0),
)

let outerArc = circleArc(p2(0, 0), outerRadius)
let innerArc = circleArc(p2(outerRadius * 0.35, outerRadius * 0.35), holeRadius)
let surf = CylinderSurface3(axisX: v3(1, 0, 0), axisY: v3(0, 0, -1), axisZ: v3(0, 1, 0), radius: 300)

let grid = surf.makeGrid([Curve2 outerArc, innerArc], resolution)
let mesh = grid.toGpu

app.run proc(ctx: DrawContext) =
  push_blendRgbx ctx

  let cameraDir = normalize(ctx.viewportMatrix.inverse * vec3(0, 0, -1))

  # faces
  ctx.fill3dMeshShadedByNormalsSingleSide(mesh, color(1.0, 0.55, 0.25) * 0.75, color(1.0, 0.55, 0.25) * 0.5)

  # edges
  for i in countup(0, grid.indices.high, 4):
    for j in 0..<4:
      ctx.fillCapsule(
        color = color(0.75, 0.75, 0.75),
        radius = holeRadius / resolution / 1000 / app.camera.zoom / 3,
        a = grid.points[grid.indices[i + j]].V3.vec3,
        b = grid.points[grid.indices[i + ((j + 1) mod 4)]].V3.vec3,
        normal = cameraDir,
      )

  # vertices
  for pt in grid.points:
    ctx.fillCircle(
      color = color(1, 1, 1),
      center = pt.V3.vec3,
      radius = holeRadius / resolution / 1000 / app.camera.zoom,
      normal = cameraDir,
    )
  
  pop_blendRgbx ctx
