## Visual test: displays triangulated grids generated by `makeGrid` on a Plane3 surface.
##
## The grid is computed from two closed 2D contours forming an outer boundary and a circular hole in the middle.

import std/[math, sequtils]
import pkg/[chroma, siwin]
import rice
import sigeo/[core, curves2d, surfaces]
import ./drawutils


type
  VisibleGrid = object
    surface: OwnedSurface3
    brep: seq[OwnedCurve2]
    color: Color
    
    grid: Grid3
    mesh: Mesh
  
  VisibleEdge = object
    surface: OwnedSurface3
    edge: OwnedCurve2
    color: Color
  
  State = object
    grids: seq[VisibleGrid]
    edges: seq[VisibleEdge]


const
  resolution = 32

let app = newVisualTest(
  title = "sigeo v_surfaceintersect",
  size = ivec2(800, 800),
  contentCenter = vec2(0, 0),
)


proc drawDots(ctx: DrawContext, pts: seq[Vec3], thickness: float = 1) =
  let cameraDir = normalize(ctx.viewportMatrix.inverse * vec3(0, 0, -1))
  for pt in pts:
    ctx.fillCircle(
      color = color(1, 1, 1),
      center = pt,
      radius = resolution / 1000 / app.camera.zoom * thickness,
      normal = cameraDir,
    )

proc drawEdge(ctx: DrawContext, surface: Surface3, edge: Curve2, thickness: float = 1, color = color(0.75, 0.75, 0.75)) =
  let cameraDir = normalize(ctx.viewportMatrix.inverse * vec3(0, 0, -1))
  for i in 0..<resolution:
    let a = edge.pointAt((i) / resolution)
    let b = edge.pointAt((i+1) / resolution)
    ctx.fillCapsule(
      color = color(0.75, 0.75, 0.75),
      radius = resolution / 5000 / app.camera.zoom / 3 * thickness,
      a = surface.pointAt(a).V3.vec3,
      b = surface.pointAt(b).V3.vec3,
      normal = cameraDir,
    )

proc drawWireframe(ctx: DrawContext, grid: Grid3, thickness: float = 1) =
  let cameraDir = normalize(ctx.viewportMatrix.inverse * vec3(0, 0, -1))
  for i in countup(0, grid.indices.high, 4):
    for j in 0..<4:
      ctx.fillCapsule(
        color = color(0.75, 0.75, 0.75),
        radius = resolution / 10000 / app.camera.zoom / 3 * thickness,
        a = grid.points[grid.indices[i + j]].V3.vec3,
        b = grid.points[grid.indices[i + ((j + 1) mod 4)]].V3.vec3,
        normal = cameraDir,
      )


proc vgrid(surface: OwnedSurface3, brep: seq[OwnedCurve2], color = color(1.0, 0.55, 0.25)): VisibleGrid =
  result.surface = surface
  result.brep = brep
  result.color = color
  result.grid = makeGrid(surface, brep.view, resolution)
  result.mesh = result.grid.toGpu

proc vedge(surface: OwnedSurface3, edge: OwnedCurve2, color = color(1.0, 0.55, 0.25)): VisibleEdge =
  result.surface = surface
  result.edge = edge
  result.color = color


var state: State


let plane1 = placement(v3(0, 0, 1).normal)
let plane2 = placement(v3(1, 1, 1).normal)
let brep = @[
  # todo: square brep do not work
  # line(p2(-300, -300), p2(300, -300)),
  # line(p2(300, -300), p2(300, 300)),
  # line(p2(300, 300), p2(-300, 300)),
  # line(p2(-300, 300), p2(-300, -300)),
  arc(p2(), 300),
]


state.grids.add vgrid(plane1.toOwnedSurface3, brep.mapIt(it.toOwnedCurve2))
state.grids.add vgrid(plane2.toOwnedSurface3, brep.mapIt(it.toOwnedCurve2), color(1, 0.2, 0.2))

for x in intersectionCurves(plane1, plane2):
  state.edges.add vedge(plane1.toOwnedSurface3, line(x.startPoint - x.toVec.normal * 300, x.startPoint + x.toVec.normal * 300).toOwnedCurve2)


app.onKey proc(e: KeyEvent) =
  ##


app.run proc(ctx: DrawContext) =
  push_blendRgbx ctx

  for x in state.grids:
    ctx.fill3dMeshShadedByNormalsSingleSide(x.mesh, x.color * 0.75, x.color * 0.5)
    # ctx.drawWireframe(x.grid)
    # ctx.drawDots(x.grid.points.mapIt(it.V3.vec3))

  for x in state.edges:
    ctx.drawEdge(x.surface, x.edge, color = x.color)

  pop_blendRgbx ctx
